/*
 * error_code.h
 *
 *  Created on: Jun 6, 2018
 *      Author: robotic_tools
 */

#ifndef LIB_ERROR_HANDLE_ERROR_CODE_H_
#define LIB_ERROR_HANDLE_ERROR_CODE_H_


#include <stdint.h>





enum class TrajectoryErrCode : uint32_t
{
	TRAJECTORY_NOT_IMPLEMENTED,
	TRAJECTORY_BUFFER_OVF,
	TRAJECTORY_PARAMS_OVF,

	ALWAYS_AT_END,
};


enum class TrajectoryRegisterErrCode : uint32_t
{
	DECODE_PROFILE_NOT_IMPLEMENTED,
	ENCODE_PROFILE_NOT_IMPLEMENTED,


	ALWAYS_AT_END,
};


enum class ProfileConcaveScurveVelErrCode : uint32_t
{
	PROFILE_CREATION_BAD_PARAMETERS,
	PROFILE_CREATION_BUFFER_OVERFLOW,
	BUFFER_REVERSE_MODE_WRONG_USE,
	BUFFER_MODE_NOT_IMPLEMENTED,
	BUFFER_WRONG_START_MODE,
	PROFILE_NOT_CREATED,



	ALWAYS_AT_END,
};

enum class DRV8880ErrCode : uint32_t
{
	MICROSTEP_PINS_NOT_SET,
	MICROSTEP_INVALID_PARAMETER,
	CURRENT_PINS_NOT_SET,
	CURRENT_INVALID_PARAMETER,

	ALWAYS_AT_END,
};


enum class DRV8880RegisterErrCode : uint32_t
{
	DECODE_MRES_NOT_IMPLEMENTED,
	ENCODE_MRES_NOT_IMPLEMENTED,
	DECODE_CURRENT_NOT_IMPLEMENTED,
	ENCODE_CURRENT_NOT_IMPLEMENTED,
	DECODE_DIRECTION_NOT_IMPLEMENTED,
	ENCODE_DIRECTION_NOT_IMPLEMENTED,


	ALWAYS_AT_END,
};


enum class PwmPfcErrCode : uint32_t
{
	BUFFER_MODE_NOT_IMPLEMENTED,
	BUFFER_REVERSE_MODE_WRONG_USE,
	INVALID_FREQUENCY_FOR_TOP_CALCULATION,
	BUFFER_WRONG_START_MODE,


	ALWAYS_AT_END,
};


enum class DRV8880MasterProtocolErrCode : uint32_t
{
	INITIALIZATION_NOT_STARTED,

	ALWAYS_AT_END,
};




#endif /* LIB_ERROR_HANDLE_ERROR_CODE_H_ */
